#!/usr/bin/env bash
# Generates ~/.config/starship.toml from sway theme variables, so the
# prompt follows a theme switch instead of staying stone forever.
#
# The same shape as generate-waybar-style.sh and generate-aerc-styleset.sh.
# Cheaper than either: starship re-reads its config on every prompt render,
# so a theme switch reaches the shell you are already sitting in - no
# `exec zsh`, no new terminal.
# Args: background-color text-color accent-color surface-color
set -u

BACKGROUND_COLOR="$1"
TEXT_COLOR="$2"
ACCENT_COLOR="$3"
SURFACE_COLOR="$4"

# starship needs six-digit hex. Given #eee it drops the whole style string
# it appears in and renders unstyled, with no error - measured against
# starship 1.26.0. Every theme in the tree spells its colours in full
# today, and palette.conf does not (#eee), so expanding here is what keeps
# a short colour from silently costing the mark its background.
expand_hex() {
  local c=$1
  if [[ $c =~ ^#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])$ ]]; then
    printf '#%s%s%s%s%s%s' \
      "${BASH_REMATCH[1]}" "${BASH_REMATCH[1]}" \
      "${BASH_REMATCH[2]}" "${BASH_REMATCH[2]}" \
      "${BASH_REMATCH[3]}" "${BASH_REMATCH[3]}"
  else
    printf '%s' "$c"
  fi
}

BACKGROUND_COLOR=$(expand_hex "$BACKGROUND_COLOR")
TEXT_COLOR=$(expand_hex "$TEXT_COLOR")
ACCENT_COLOR=$(expand_hex "$ACCENT_COLOR")
SURFACE_COLOR=$(expand_hex "$SURFACE_COLOR")

CONFIG="$HOME/.config/starship.toml"
mkdir -p "$(dirname "$CONFIG")"

cat > "$CONFIG" <<EOF
# Auto-generated by generate-starship-config.sh - changes will be
# overwritten on theme switch. See /etc/skel/.config/starship.toml for why
# the mark is one glyph and not the logo.

format = """
[▄█▀ ](fg:${TEXT_COLOR} bg:${SURFACE_COLOR})\\
[](fg:${SURFACE_COLOR} bg:${BACKGROUND_COLOR})\\
[ \$directory](bg:${BACKGROUND_COLOR})\\
[](fg:${BACKGROUND_COLOR})\\
\$git_branch\\
\$git_status\\
\$fill\\
\$cmd_duration\\
\$line_break\\
\$character"""

[directory]
style = "fg:${TEXT_COLOR} bg:${BACKGROUND_COLOR}"
format = "[\$path](\$style)[\$read_only](\$read_only_style)"
truncation_length = 3
truncate_to_repo = true
read_only = " ro"
read_only_style = "fg:${ACCENT_COLOR} bg:${BACKGROUND_COLOR}"

[git_branch]
symbol = " "
style = "fg:${ACCENT_COLOR}"
format = " [\$symbol\$branch](\$style)"

[git_status]
style = "fg:${ACCENT_COLOR}"
format = " [\$all_status\$ahead_behind](\$style)"
conflicted = "!"
untracked = "?"
modified = "*"
staged = "+"
renamed = "»"
deleted = "x"
stashed = "\$"
ahead = "^\${count}"
behind = "v\${count}"
diverged = "^\${ahead_count}v\${behind_count}"

[fill]
symbol = " "

[cmd_duration]
min_time = 2000
style = "fg:${ACCENT_COLOR}"
format = "[\$duration](\$style)"

[character]
success_symbol = "[❯](fg:${ACCENT_COLOR})"
error_symbol = "[❯](fg:${TEXT_COLOR})"
vimcmd_symbol = "[❮](fg:${ACCENT_COLOR})"
EOF
