#!/usr/bin/env bash
# Generates ~/.config/starship.toml from sway theme variables, so the
# prompt follows a theme switch.
#
# The same shape as generate-waybar-style.sh and generate-aerc-styleset.sh.
# Cheaper than either: starship re-reads its config on every prompt render,
# so a theme switch reaches the shell you are already sitting in - no
# `exec zsh`, no new terminal.
#
# The layout is starship's catppuccin-powerline preset (`starship preset
# catppuccin-powerline`, starship 1.26.0), changed in four places:
#   - the $os segment is the AshlarOS mark, U+F8FE from AshlarOS Symbols
#     (ashlaros-branding). The [os] module would resolve our ID=ashlaros
#     to plain Linux and probe the OS on every prompt to print a constant.
#     Followed by a space: the glyph is two cells wide, and foot draws it
#     into the next cell only when that cell is blank.
#   - both outer ends are square, not rounded, to fit the brick shapes;
#     the right end is an arrow and replaces the prompt character.
#   - no $line_break and no $character: one line, ending in that arrow.
#   - the preset's four catppuccin palettes are one, "ashlaros", written
#     from the theme.
#
# Args: the preset's palette names, from the theme's $prompt-* variables
# (every theme.conf defines them; see /etc/sway/definitions):
#   crust red peach yellow green sapphire lavender
set -u

# starship needs six-digit hex. Given #eee it drops the whole style string
# it appears in and renders unstyled, with no error - measured against
# starship 1.26.0. palette.conf spells the foreground #eee, so expanding
# here is what keeps a short colour from silently costing a segment.
expand_hex() {
  local c=$1
  if [[ $c =~ ^#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])$ ]]; then
    printf '#%s%s%s%s%s%s' \
      "${BASH_REMATCH[1]}" "${BASH_REMATCH[1]}" \
      "${BASH_REMATCH[2]}" "${BASH_REMATCH[2]}" \
      "${BASH_REMATCH[3]}" "${BASH_REMATCH[3]}"
  else
    printf '%s' "$c"
  fi
}

CRUST=$(expand_hex "$1")
RED=$(expand_hex "$2")
PEACH=$(expand_hex "$3")
YELLOW=$(expand_hex "$4")
GREEN=$(expand_hex "$5")
SAPPHIRE=$(expand_hex "$6")
LAVENDER=$(expand_hex "$7")

CONFIG="$HOME/.config/starship.toml"
mkdir -p "$(dirname "$CONFIG")"

cat > "$CONFIG" <<EOF
# Auto-generated by generate-starship-config.sh - changes will be
# overwritten on theme switch.

"\$schema" = 'https://starship.rs/config-schema.json'

format = """
[  ](fg:crust bg:red)\\
\$username\\
[](bg:peach fg:red)\\
\$directory\\
[](bg:yellow fg:peach)\\
\$git_branch\\
\$git_status\\
[](fg:yellow bg:green)\\
\$c\\
\$rust\\
\$golang\\
\$nodejs\\
\$bun\\
\$php\\
\$java\\
\$kotlin\\
\$haskell\\
\$python\\
[](fg:green bg:sapphire)\\
\$conda\\
[](fg:sapphire bg:lavender)\\
\$time\\
[ ](fg:lavender)\\
\$cmd_duration"""

palette = 'ashlaros'


[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ \$user](\$style)'

[directory]
style = "bg:peach fg:crust"
format = "[ \$path ](\$style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ \$symbol \$branch ](fg:crust bg:yellow)](\$style)'

[git_status]
style = "bg:yellow"
format = '[[(\$all_status\$ahead_behind )](fg:crust bg:yellow)](\$style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[bun]
symbol = ""
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ \$symbol( \$version) ](fg:crust bg:green)](\$style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ \$symbol( \$version)(\\(#\$virtualenv\\)) ](fg:crust bg:green)](\$style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ \$symbol( \$context) ](fg:crust bg:sapphire)](\$style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[\$symbol\$environment ](\$style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  \$time ](fg:crust bg:lavender)](\$style)'

[cmd_duration]
show_milliseconds = true
format = " in \$duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000


[palettes.ashlaros]
red = "${RED}"
peach = "${PEACH}"
yellow = "${YELLOW}"
green = "${GREEN}"
sapphire = "${SAPPHIRE}"
lavender = "${LAVENDER}"
crust = "${CRUST}"
EOF
