#!/usr/bin/env bash
# Generates ~/.config/aerc/stylesets/ashlaros from sway theme variables, so
# the mail client follows a theme switch instead of desynchronising from it
# the first time someone changes theme.
#
# The same shape as generate-waybar-style.sh: only the generated file is
# overwritten, and accounts.conf/aerc.conf are the user's own.
# Args: background-color text-color accent-color error-color warning-color
set -u

BACKGROUND_COLOR="$1"
TEXT_COLOR="$2"
ACCENT_COLOR="$3"
ERROR_COLOR="$4"
WARNING_COLOR="$5"

STYLESET_DIR="$HOME/.config/aerc/stylesets"
mkdir -p "$STYLESET_DIR"

# *.default=true resets to the terminal's own colours first; without it the
# keys below are layered over aerc's built-in defaults and the result is a
# mixture of two palettes.
cat > "$STYLESET_DIR/ashlaros" <<EOF
# Auto-generated by generate-aerc-styleset.sh — overwritten on theme switch
*.default=true
*.normal=true

default.fg=${TEXT_COLOR}
default.bg=${BACKGROUND_COLOR}

error.fg=${ERROR_COLOR}
warning.fg=${WARNING_COLOR}
success.fg=${ACCENT_COLOR}

border.fg=${ACCENT_COLOR}

title.fg=${BACKGROUND_COLOR}
title.bg=${ACCENT_COLOR}
title.bold=true

tab.fg=${TEXT_COLOR}
tab.bg=${BACKGROUND_COLOR}
tab.selected.fg=${BACKGROUND_COLOR}
tab.selected.bg=${ACCENT_COLOR}
tab.selected.bold=true

header.fg=${ACCENT_COLOR}
header.bold=true

msglist_unread.bold=true
msglist_flagged.fg=${WARNING_COLOR}
msglist_result.fg=${ACCENT_COLOR}
msglist_*.selected.bg=${ACCENT_COLOR}
msglist_*.selected.fg=${BACKGROUND_COLOR}

dirlist_*.selected.bg=${ACCENT_COLOR}
dirlist_*.selected.fg=${BACKGROUND_COLOR}

statusline_default.fg=${TEXT_COLOR}
statusline_default.bg=${BACKGROUND_COLOR}
statusline_error.fg=${ERROR_COLOR}
statusline_success.fg=${ACCENT_COLOR}

completion_default.fg=${TEXT_COLOR}
completion_default.bg=${BACKGROUND_COLOR}
completion_pill.bg=${ACCENT_COLOR}
completion_pill.fg=${BACKGROUND_COLOR}

selector_focused.bg=${ACCENT_COLOR}
selector_focused.fg=${BACKGROUND_COLOR}
selector_chooser.bold=true
EOF
