#!/usr/bin/env bash
# Generates ~/.config/swaylock/config from sway theme variables, so the
# lock screen is the same desktop rather than swaylock's stock light grey.
#
# The same shape as generate-waybar-style.sh and generate-aerc-styleset.sh.
# swaylock reads $XDG_CONFIG_HOME/swaylock/config by default - checked
# against the binary's own search list - so lock.sh needs no --config and
# a user who prefers their own keeps it by disabling the theme hook.
#
# Colours are written without the leading '#': swaylock wants RRGGBBAA or
# RRGGBB and rejects the hash with "invalid color", which on a lock screen
# is a process that will not start and a session nobody can unlock.
#
# Args: background-color text-color accent-color error-color surface-color
set -u

BACKGROUND_COLOR="$1"
TEXT_COLOR="$2"
ACCENT_COLOR="$3"
ERROR_COLOR="$4"
SURFACE_COLOR="$5"

# swaylock takes RRGGBB or RRGGBBAA, never a leading hash, and a short #eee
# is not a form it accepts at all - palette.conf spells the foreground that
# way, so anything copying it verbatim would break here.
hex() {
	local c=${1#\#}
	if [ ${#c} = 3 ]; then
		c="${c:0:1}${c:0:1}${c:1:1}${c:1:1}${c:2:1}${c:2:1}"
	fi
	printf '%s' "$c"
}

BG=$(hex "$BACKGROUND_COLOR")
FG=$(hex "$TEXT_COLOR")
ACCENT=$(hex "$ACCENT_COLOR")
ERROR=$(hex "$ERROR_COLOR")
SURFACE=$(hex "$SURFACE_COLOR")

CONFIG="$HOME/.config/swaylock/config"
mkdir -p "$(dirname "$CONFIG")"

# The ring carries the state, which is the whole information the screen
# has to convey: accent while typing, surface when empty, error when the
# password was wrong. Everything else stays the desktop's own colours.
cat > "$CONFIG" <<EOF
# Auto-generated by generate-swaylock-config.sh - overwritten on theme
# switch. Put your own in ~/.config/swaylock/ after disabling the theme
# hook, or accept that the lock screen follows the theme.

daemonize
show-failed-attempts
indicator-radius=100
indicator-thickness=8

color=${BG}

inside-color=${BG}
inside-clear-color=${BG}
inside-ver-color=${BG}
inside-wrong-color=${BG}
inside-caps-lock-color=${BG}

ring-color=${SURFACE}
ring-clear-color=${ACCENT}
ring-ver-color=${ACCENT}
ring-wrong-color=${ERROR}
ring-caps-lock-color=${ACCENT}

key-hl-color=${ACCENT}
bs-hl-color=${ERROR}
caps-lock-key-hl-color=${ACCENT}
caps-lock-bs-hl-color=${ERROR}
separator-color=${BG}

line-color=${BG}
line-clear-color=${BG}
line-ver-color=${BG}
line-wrong-color=${BG}
line-caps-lock-color=${BG}

text-color=${FG}
text-clear-color=${FG}
text-ver-color=${FG}
text-wrong-color=${ERROR}
text-caps-lock-color=${FG}

layout-bg-color=${BG}
layout-border-color=${SURFACE}
layout-text-color=${FG}
EOF
